sudo: required
language: scala
scala:
- 2.12.8
services:
- scooby
jobs:
  include:
  - stage: test
    script:
    - sbt "^^ 1.2.8" clean update test
    jdk: oraclejdk8

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/
    - $HOME/.sbt/
